openapi: 3.0.0
components:
  schemas:
    Especie:
      properties:
        id:
          type: string
        nombre:
          type: string
        clasificacion:
          type: string
        designacion:
          type: string
        altura_promedio:
          type: string
        tiempo_de_vida_promedio:
          type: string
        color_ojo:
          type: string
        color_cabello:
          type: string
        color_piel:
          type: string
        lenguaje:
          type: string
        mundo_hogar:
          type: string
        personas:
          type: string
        peliculas:
          type: string
        url:
          type: string
        creado:
          type: string
        editado:
          type: string
    EspecieCreada:
      properties:
        status:
          type: string
        number_records:
          type: number
        message:
          type: string
        data:
          type: object
          properties:
            id:
              type: string
            nombre:
              type: string
            clasificacion:
              type: string
            designacion:
              type: string
            altura_promedio:
              type: string
            tiempo_de_vida_promedio:
              type: string
            color_ojo:
              type: string
            color_cabello:
              type: string
            color_piel:
              type: string
            lenguaje:
              type: string
            mundo_hogar:
              type: string
            personas:
              type: string
            peliculas:
              type: string
            url:
              type: string
            creado:
              type: string
            editado:
              type: string
    ErrorReponse:
      properties:
        status:
          type: string
        number_records:
          type: number
        message:
          type: string
        data:
          type: object
  securitySchemes: {}
info:
  title: Serverless
  description: NodeJS API with serverless framework and integrated with SWAPI
  version: '1'
paths:
  //species:
    post:
      operationId: createSpecie
      summary: Creacion de especies
      description: Creacion de especies del universo de Star Wars
      responses:
        '201':
          description: Status 201 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EspecieCreada'
        '500':
          description: Status 500 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReponse'
